name: Maven Run Tests when push to main branch and development

on:
  # Trigger the workflow on push for the main branch
  # and pull request for main and card-* prefix branches
  push:
    branches:
      - main
    pull_request:
      branches:
        - main
        - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '18'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Test with Maven
        run: mvn -B test --file pom.xml
